import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Footer from "./components/Footer";



const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});


// Metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={poppins.className}>








        {/* Navbar Component */}

        <div> {children}</div>


        {/* Main content */}

        {/* Footer Component */}
        <Footer />

      </body>
    </html>
  );
}
